# Generated by Django 4.0.4 on 2022-06-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000)),
                ('address', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000)),
                ('username', models.CharField(max_length=10000)),
                ('bio', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000)),
                ('email', models.CharField(max_length=10000)),
                ('specialty', models.CharField(max_length=10000)),
                ('date_appointment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000)),
                ('username', models.CharField(max_length=10000)),
                ('email', models.CharField(max_length=10000)),
                ('case', models.CharField(max_length=100000)),
                ('date_appointment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=10000)),
                ('post_content', models.CharField(max_length=100000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000)),
                ('category', models.CharField(max_length=10000)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
