# Generated by Django 4.0.4 on 2022-06-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_date_appointment_doctor_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='specialist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
