# Generated by Django 4.0.4 on 2022-06-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_people_specialist_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor'),
        ),
    ]
