# Generated by Django 4.0.4 on 2022-06-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_post_rename_name_addres_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='street',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='bio',
            name='usernames',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addres'),
        ),
    ]
