# Generated by Django 4.0.4 on 2022-06-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_addres_street_alter_bio_usernames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='0.00', max_length=10000),
        ),
    ]
